#### Install package

In [ ]:
!pip install sktime
!pip install delayed

In [ ]:
import pandas as pd
import numpy as np
from datetime import datetime
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from sklearn.preprocessing import RobustScaler, StandardScaler
import datetime 

import warnings
warnings.filterwarnings('ignore')
pd.options.display.float_format = '{:.5f}'.format

## 쇼핑몰 코드 (모델 학습)

### 날짜 지역 가격 INDEX 쇼핑몰 코드별로 CSV파일 생성

In [ ]:
final_df = pd.read_pickle('fc주문_통합_수정.pkl')

In [ ]:
final_df.head()

  CORP_ID        REF_ORD_NO BKG_TYP  ...         평균가격      metric cluster
0   KX007  2021030365922551       7  ...  14900.00000   134265392     8.0
1   KX007  2021030365922951       7  ...  20529.68342  4610261043     0.0
2   KX007  2021030365924361       7  ...  27175.94846  4936599538     8.0
3   KX007  2021030365928921       7  ... 102245.81445  3858391637     8.0
4   KX007  2021030365930451       7  ...  39800.00000  4631307460     8.0

[5 rows x 24 columns]

In [ ]:
# 클러스터 결측값를 10으로 채워넣음
final_df['cluster'].replace({'nan':'10'},inplace = True)

In [ ]:
# 평균가격 구하기(단순 나누기)
final_df['ITEM_PRICE'] = final_df.apply(lambda x: x['ITEM_AMT']/x['ITEM_QTY'], axis = 1)

In [ ]:
final_df.SHPR_CD.unique()

array(['90001302', '90001441', '90001542', '90001341', '90001541',
       '90001443', '90001381', '90001521', '90001582', '90001602',
       '90001662', '90001622', '90001682', '90001683', '90001702',
       '90001703', '90001705', '90001704', '90001664', '90001768',
       '90001765', '90001776', '90001774', '90001842'], dtype=object)

In [ ]:
final_df.columns

Index(['CORP_ID', 'REF_ORD_NO', 'BKG_TYP', 'BKG_DATE', 'BKG_TIME', 'SHPR_CD',
       'INV_AMT', 'ITEM_CD', 'ITEM_QTY', 'ITEM_AMT', 'REF_ITEM_SEQ',
       'DLVPREARRBRANCD', 'DLVPREARREMPNICKNM', 'DLVCLSFCD', 'DLVSUBCLSFCD',
       'POST_ZONE', 'SHPR_ADDR_1', 'SHPR_ADDR_2', 'CNEE_ADDR_1', 'CNEE_ADDR_2',
       '개별가격', '평균가격', 'metric', 'cluster', 'ITEM_PRICE'],
      dtype='object')

In [ ]:
hc = pd.read_csv("./holiday_cleaned.csv")

In [ ]:
hc.head()

           날짜    설명  요일  휴일여부
0  2018-01-01    새해   0     1
1  2018-01-02  해당없음   1     0
2  2018-01-03  해당없음   2     0
3  2018-01-04  해당없음   3     0
4  2018-01-05  해당없음   4     0

In [ ]:
hc['날짜'] = hc['날짜'].apply(lambda x: datetime.datetime.strptime(x,'%Y-%m-%d'))

In [ ]:
hc = hc[(hc['날짜']>='2021-03-01') &(hc['날짜']<='2021-06-30')]

In [ ]:
hc.head()

             날짜    설명  요일  휴일여부
1155 2021-03-01   삼일절   0     1
1156 2021-03-02  해당없음   1     0
1157 2021-03-03  해당없음   2     0
1158 2021-03-04  해당없음   3     0
1159 2021-03-05  해당없음   4     0

In [ ]:
hc = hc[['날짜','요일','휴일여부']]

In [ ]:
hc.columns = ['BKG_DATE', '요일','휴일여부']

### 누락 컬럼 생성

In [ ]:
# shpr_cd 분리 때문에 비어있는 컬럼 확인하기 위해 컬럼 생성
calt = list(final_df.CNEE_ADDR_1.unique())
cllt = list(final_df.cluster.unique())
tlt = calt+cllt

In [ ]:
# 누락 되어있는 컬럼으로 dataframe 생성 
def make_df(temp):
  collist = []
  for i in tlt:
    if i in temp.columns:
      pass
    else : 
      collist.append(i)
  cdf = pd.DataFrame(columns = collist)
  return cdf

### 최종 전처리

In [ ]:
def preprocessing(df, hc):
  date = pd.DataFrame(pd.period_range('2021-03-01', '2021-06-30'))
  date.columns = ['BKG_DATE']
  date['BKG_DATE'] = date['BKG_DATE'].apply(lambda x: x.to_timestamp())
  for i in df.SHPR_CD.unique():
    # temp_df : df를 shpr_cd별로 끊어 쓰기
    temp_df = df[df['SHPR_CD']==i]
    
    # 일별로 1개의 컬럼만 존재하게끔 output dataframe 구성
    tmp =temp_df.groupby(['BKG_DATE'])['ITEM_QTY'].sum().reset_index()
    tmp1 =temp_df.groupby(['BKG_DATE'])['ITEM_QTY'].sum().reset_index()
    tmp2 =temp_df.groupby(['BKG_DATE'])['ITEM_QTY'].sum().reset_index()
    tmp3 =temp_df.groupby(['BKG_DATE'])['ITEM_QTY'].sum().reset_index()
    
    # 일별 group by한 dataframe을 0301-0630사이 날짜 dataframe에 merge
    # 매출이 없는 날의 경우, 결측값을 0으로 처리
    tmp = pd.merge(date, tmp, on = 'BKG_DATE', how='left')
    tmp.fillna(0, inplace = True)

    # 휴일 merge
    tmp = pd.merge(tmp, hc, how = 'left', on = 'BKG_DATE')

    # 하루전, 2일전, 3일전 판매개수
    tmp1['BKG_DATE']=tmp1['BKG_DATE']+datetime.timedelta(1)
    tmp2['BKG_DATE']=tmp2['BKG_DATE']+datetime.timedelta(2)
    tmp3['BKG_DATE']=tmp3['BKG_DATE']+datetime.timedelta(3)
    tmp1=tmp1.rename(columns={'ITEM_QTY':'DAY_1'})
    tmp2=tmp2.rename(columns={'ITEM_QTY':'DAY_2'})
    tmp3=tmp3.rename(columns={'ITEM_QTY':'DAY_3'})
    DAY_df = pd.merge(tmp, tmp1, how = 'left', on=['BKG_DATE'])
    DAY_df = pd.merge(DAY_df, tmp2, how = 'left', on=['BKG_DATE'])
    DAY_df = pd.merge(DAY_df, tmp3, how = 'left', on=['BKG_DATE'])
    
    # 첫날 개수는 0으로 처리
    DAY_df=DAY_df.fillna(0)
    # 주별 물품 개수 합계
    DAY_df['week'] = DAY_df['BKG_DATE'].apply(lambda x: x.isocalendar()[1])
    DAY_df['week'] = DAY_df['week'].apply(lambda x: x-8)
    dfn= DAY_df.groupby(['week'])['ITEM_QTY'].sum().reset_index()
    dfn=dfn.rename(columns={'ITEM_QTY':'WEEK_AMT'})
    last_df = pd.merge(DAY_df, dfn, how = 'left', on=['week'])

    # 품목 가격 범주화
    plist = [100, 27307.5, 63200, 133375, 290100, 1170901]
    for x in range(1,6):
      start = plist[x-1]
      end = plist[x]
      # 범주별 cut
      ppdf = temp_df[(temp_df["ITEM_PRICE"] >= start) & (temp_df["ITEM_PRICE"] < end)]
      # 범주로 cut 된 dataframe에서 일별 groupby 후 
      gbpdf = ppdf.groupby(['BKG_DATE'])['ITEM_QTY'].sum().reset_index()
      colname = "{}이상 {}미만".format(start, end)
      gbpdf.columns = ['BKG_DATE',colname]
      last_df = pd.merge(last_df, gbpdf, how = 'left', on = ['BKG_DATE'])

    # 일별 최대 최소 가격
    df3=temp_df.groupby(['BKG_DATE'])['ITEM_PRICE'].mean().reset_index()
    df3=df3.rename(columns={'ITEM_PRICE':'MEAN_PRICE'})
    last_df = pd.merge(last_df, df3, how = 'left', on = ['BKG_DATE'])

    # 지역별 판매량 group by 후 pivot table
    cneedf = temp_df.groupby(['BKG_DATE','CNEE_ADDR_1'])['ITEM_QTY'].sum().reset_index()
    cneedf = cneedf.pivot(index = 'BKG_DATE', columns = 'CNEE_ADDR_1', values = 'ITEM_QTY')
    last_df = pd.merge(last_df, cneedf, how = 'left', on = 'BKG_DATE')
    last_df.fillna(0, inplace = True)

    cludf = temp_df.groupby(['BKG_DATE','cluster'])['ITEM_QTY'].sum().reset_index()
    cludf = cludf.pivot(index = 'BKG_DATE', columns = 'cluster', values = 'ITEM_QTY')
    last_df = pd.merge(last_df, cludf, how = 'left', on = 'BKG_DATE')
    last_df.fillna(0, inplace = True)
    last_df=last_df.drop('week',axis=1)
    cdf = make_df(last_df)
    final = pd.concat([last_df, cdf], axis=1)
    final.fillna(0, inplace=True)
    final = final[['BKG_DATE', 'ITEM_QTY', '요일', '휴일여부', 'DAY_1', 'DAY_2', 'DAY_3',
       'WEEK_AMT', '100이상 27307.5미만', '27307.5이상 63200미만', '63200이상 133375미만',
       '133375이상 290100미만', '290100이상 1170901미만', 'MEAN_PRICE', '강원', '경기',
       '경남', '경북', '광주', '대구', '대전', '부산', '서울', '세종', '울산', '인천', '전남', '전북',
       '제주', '충남', '충북', '0.0', '1.0', '10', '2.0', '3.0', '4.0', '5.0', '6.0',
       '7.0', '8.0', '9.0']]

    final.to_pickle("./shpr_cd_"+i+".pkl")

In [ ]:
preprocessing(final_df, hc)