#### install package

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import datetime
import os
import plotly.express as px
import folium
import plotly.express as px
from fbprophet import Prophet

import warnings
warnings.filterwarnings('ignore')
pd.options.display.float_format = '{:.5f}'.format

In [ ]:
fc_df = pd.read_pickle('./시계열/fc주문_통합_수정.pkl')
display(fc_df)

        CORP_ID        REF_ORD_NO BKG_TYP  ...         평균가격      metric cluster
0         KX007  2021030365922551       7  ...  14900.00000   134265392     8.0
1         KX007  2021030365922951       7  ...  20529.68342  4610261043     0.0
2         KX007  2021030365924361       7  ...  27175.94846  4936599538     8.0
3         KX007  2021030365928921       7  ... 102245.81445  3858391637     8.0
4         KX007  2021030365930451       7  ...  39800.00000  4631307460     8.0
...         ...               ...     ...  ...          ...         ...     ...
1744402   GP001  2021063088148031       7  ...  12000.00000  4782863820     3.0
1744403   GP001  2021063073024911       7  ... 100000.00000  2055189125     3.0
1744404   GP001  2021063087455441       7  ...  38500.00000         NaN     nan
1744405   KX007  2021062966256441       7  ...  62900.00000  5525868431     6.0
1744406   KX007  2021063082592751       7  ... 101714.28571  5054805158     1.0

[1744407 rows x 24 columns]

In [ ]:
fc_df_shpr = fc_df.groupby(by = ['SHPR_CD', 'CORP_ID'])['REF_ORD_NO'].count()
fc_df_shpr.sort_values(ascending = False)

SHPR_CD   CORP_ID
90001302  KX007      447804
90001542  KX007      203993
90001341  KX007      168257
90001541  KX007      147525
90001441  KX007      124877
90001602  KX007      110149
90001443  KX007       99763
90001582  KX007       82117
90001622  KX007       67980
90001521  KX007       58123
90001703  GP001       56899
90001682  KX007       36227
90001702  GP001       30639
90001776  GP001       24371
90001705  GP001       24022
90001704  GP001       20352
90001768  GP001       12860
90001662  KX007        8218
90001765  GP001        6262
90001683  KX007        5855
90001381  KX007        5433
90001664  GP001        1909
90001774  GP001         730
90001842  GP001          42
Name: REF_ORD_NO, dtype: int64

In [ ]:
fc_df['year'] = fc_df['BKG_DATE'].apply(lambda x: x.year)
fc_df['month'] = fc_df['BKG_DATE'].apply(lambda x: x.month)
fc_df['day'] = fc_df['BKG_DATE'].apply(lambda x: x.day)
fc_df['weekday'] = fc_df['BKG_DATE'].apply(lambda x: x.weekday())
fc_df['week'] = fc_df['BKG_DATE'].apply(lambda x: x.isocalendar()[1])

display(fc_df)

        CORP_ID        REF_ORD_NO BKG_TYP   BKG_DATE  ... month day  weekday week
0         KX007  2021030365922551       7 2021-03-03  ...     3   3        2    9
1         KX007  2021030365922951       7 2021-03-03  ...     3   3        2    9
2         KX007  2021030365924361       7 2021-03-03  ...     3   3        2    9
3         KX007  2021030365928921       7 2021-03-03  ...     3   3        2    9
4         KX007  2021030365930451       7 2021-03-03  ...     3   3        2    9
...         ...               ...     ...        ...  ...   ...  ..      ...  ...
1744402   GP001  2021063088148031       7 2021-06-30  ...     6  30        2   26
1744403   GP001  2021063073024911       7 2021-06-30  ...     6  30        2   26
1744404   GP001  2021063087455441       7 2021-06-30  ...     6  30        2   26
1744405   KX007  2021062966256441       7 2021-06-29  ...     6  29        1   26
1744406   KX007  2021063082592751       7 2021-06-30  ...     6  30        2   26

[1744407 rows x 29 columns]

## 세대원수별

### 세대원수별 데이터 전처리

In [ ]:
hh_df = pd.read_csv('./외부 데이터/세대원수별 세대수 전처리.csv', encoding = 'utf-8')
display(hh_df)

             행정구역      행정구역코드  ...  2105 5인이상세대 비율  2106 5인이상세대 비율
0             전국   1000000000  ...         0.04580         0.04560
1          서울특별시   1100000000  ...         0.04120         0.04100
2       서울특별시 종로구  1111000000  ...         0.03880         0.03860
3        서울특별시 중구  1114000000  ...         0.03290         0.03270
4       서울특별시 용산구  1117000000  ...         0.03670         0.03670
..            ...         ...  ...             ...             ...
242      경상남도 거창군  4888000000  ...         0.04420         0.04330
243      경상남도 합천군  4889000000  ...         0.02950         0.02890
244      제주특별자치도   5000000000  ...         0.06440         0.06380
245   제주특별자치도 제주시  5011000000  ...         0.06670         0.06630
246  제주특별자치도 서귀포시  5013000000  ...         0.05800         0.05810

[247 rows x 26 columns]

In [ ]:
hh_df['행정구역_시도'] = hh_df['행정구역'].apply(lambda x: x.split(' ')[0])
hh_df['행정구역_시군구'] = hh_df['행정구역'].apply(lambda x: x.split(' ')[1])

In [ ]:
hh_df.head()

        행정구역      행정구역코드  2103 전체세대  ...  2106 5인이상세대 비율  행정구역_시도  행정구역_시군구
0        전국   1000000000   23157385  ...         0.04560       전국
1     서울특별시   1100000000    4400403  ...         0.04100    서울특별시
2  서울특별시 종로구  1111000000      74113  ...         0.03860    서울특별시       종로구
3   서울특별시 중구  1114000000      63746  ...         0.03270    서울특별시        중구
4  서울특별시 용산구  1117000000     112881  ...         0.03670    서울특별시       용산구

[5 rows x 28 columns]

In [ ]:
df2 = hh_df[hh_df['행정구역_시군구'] == '']
df2

         행정구역      행정구역코드  2103 전체세대  ...  2106 5인이상세대 비율  행정구역_시도  행정구역_시군구
0         전국   1000000000   23157385  ...         0.04560       전국
1      서울특별시   1100000000    4400403  ...         0.04100    서울특별시
27     부산광역시   2600000000    1527830  ...         0.03960    부산광역시
44     대구광역시   2700000000    1060866  ...         0.04220    대구광역시
53     인천광역시   2800000000    1272361  ...         0.04700    인천광역시
64     광주광역시   2900000000     636160  ...         0.05100    광주광역시
70     대전광역시   3000000000     655196  ...         0.04580    대전광역시
76     울산광역시   3100000000     478528  ...         0.04420    울산광역시
82   세종특별자치시   3600000000     146763  ...         0.06100  세종특별자치시
83   세종특별자치시   3611000000     146763  ...         0.06100  세종특별자치시
84       경기도   4100000000    5719333  ...         0.05170      경기도
116      강원도   4200000000     735644  ...         0.04060      강원도
135     충청북도   4300000000     747313  ...         0.04360     충청북도
147     충청남도   4400000000     985844  ...         0.04560     충청남도
163     전라북도   4500000000     839942  ...         0.04900     전라북도
178     전라남도   4600000000     895024  ...         0.04550     전라남도
201     경상북도   4700000000    1262718  ...         0.03720     경상북도
225     경상남도   4800000000    1490880  ...         0.04400     경상남도
244  제주특별자치도   5000000000     302580  ...         0.06380  제주특별자치도

[19 rows x 28 columns]

In [ ]:
df2 = df2.drop(index=82, axis=0)

In [ ]:
## 행정구역_시도 이름 변경
df2.행정구역_시도.replace({'서울특별시':'서울', '부산광역시':'부산', '대전광역시':'대전', 
                     '인천광역시':'인천','대구광역시':'대구','광주광역시':'광주',
                     '제주특별자치도':'제주','울산광역시':'울산','세종특별자치시':'세종', 
                     '경상남도': '경남', '경기도':'경기','전라북도':'전북','충청남도':'충남', 
                     '경상북도':'경북','강원도':'강원', '전라남도':'전남','충청북도':'충북',
                     '대구시':'대구','부산시':'부산','인천시':'인천'},inplace=True)

In [ ]:
df2 = df2[df2['행정구역_시도']!='전국']
df2.head()

      행정구역      행정구역코드  2103 전체세대  ...  2106 5인이상세대 비율  행정구역_시도  행정구역_시군구
1   서울특별시   1100000000    4400403  ...         0.04100       서울
27  부산광역시   2600000000    1527830  ...         0.03960       부산
44  대구광역시   2700000000    1060866  ...         0.04220       대구
53  인천광역시   2800000000    1272361  ...         0.04700       인천
64  광주광역시   2900000000     636160  ...         0.05100       광주

[5 rows x 28 columns]

In [ ]:
df2 = df2[['행정구역_시도','2103 전체세대', '2104 전체세대', '2105 전체세대', '2106 전체세대',
       '2103 1인세대 비율', '2104 1인세대 비율', '2105 1인세대 비율', '2106 1인세대 비율',
       '2103 2인세대 비율', '2104 2인세대 비율', '2105 2인세대 비율', '2106 2인세대 비율',
       '2103 3인세대 비율', '2104 3인세대 비율', '2105 3인세대 비율', '2106 3인세대 비율',
       '2103 4인세대 비율', '2104 4인세대 비율', '2105 4인세대 비율', '2106 4인세대 비율',
       '2103 5인이상세대 비율', '2104 5인이상세대 비율', '2105 5인이상세대 비율', '2106 5인이상세대 비율']]

In [ ]:
melt_df = pd.melt(df2, id_vars=['행정구역_시도'], var_name= '월별세대수', value_name='세대수')
melt_df.head()

  행정구역_시도      월별세대수           세대수
0      서울  2103 전체세대 4400403.00000
1      부산  2103 전체세대 1527830.00000
2      대구  2103 전체세대 1060866.00000
3      인천  2103 전체세대 1272361.00000
4      광주  2103 전체세대  636160.00000

In [ ]:
melt_df['month'] = melt_df['월별세대수'].apply(lambda x : x[2:4])
melt_df['세대원수'] = melt_df['월별세대수'].apply(lambda x : x[5:7])

In [ ]:
melt_df.head()

  행정구역_시도      월별세대수           세대수 month 세대원수
0      서울  2103 전체세대 4400403.00000    03   전체
1      부산  2103 전체세대 1527830.00000    03   전체
2      대구  2103 전체세대 1060866.00000    03   전체
3      인천  2103 전체세대 1272361.00000    03   전체
4      광주  2103 전체세대  636160.00000    03   전체

In [ ]:
melt_df = melt_df[['행정구역_시도', '세대수', 'month', '세대원수']]

In [ ]:
df = melt_df.pivot(index = ['행정구역_시도','month'], columns = '세대원수', values='세대수')

### 세대원수별 최종 데이터

In [ ]:
df = df.reset_index()

In [ ]:
df.head()

세대원수 행정구역_시도 month      1인      2인      3인      4인      5인            전체
0         강원    03 0.43360 0.25750 0.15220 0.11540 0.04130  735644.00000
1         강원    04 0.43440 0.25780 0.15190 0.11470 0.04120  735644.00000
2         강원    05 0.43440 0.25850 0.15180 0.11440 0.04090  736980.00000
3         강원    06 0.43500 0.25900 0.15150 0.11390 0.04060  738068.00000
4         경기    03 0.35980 0.22390 0.18700 0.17670 0.05260 5719333.00000

In [ ]:
df.columns = ['시도', 'month', '1인', '2인', '3인', '4인', '5인', '전체']

In [ ]:
df.to_pickle('지역별세대원수별인구수.pkl')

## 성/연령별

### 성/연령별 데이터 전처리

In [ ]:
ys_df = pd.read_csv('./외부 데이터/연령별_성별_인구_전처리_1026.csv', encoding = 'utf-8')
display(ys_df.head())

        행정구역      행정구역코드  2103 총인구수  ...  2104 여성 비율  2105 여성 비율  2106 여성 비율
0     서울특별시   1100000000    9598484  ...     0.51380     0.51390     0.51400
1  서울특별시 종로구  1111000000     147296  ...     0.51350     0.51360     0.51390
2   서울특별시 중구  1114000000     124552  ...     0.51170     0.51190     0.51210
3  서울특별시 용산구  1117000000     229013  ...     0.51900     0.51870     0.51870
4  서울특별시 성동구  1120000000     291906  ...     0.51200     0.51200     0.51220

[5 rows x 58 columns]

In [ ]:
ys_df['행정구역_시도'] = ys_df['행정구역'].apply(lambda x: x.split(' ')[0])
ys_df['행정구역_시군구'] = ys_df['행정구역'].apply(lambda x: x.split(' ')[1])

In [ ]:
df5 = ys_df[ys_df['행정구역_시군구'] == '']

In [ ]:
df5.행정구역_시도.replace({'서울특별시':'서울', '부산광역시':'부산', '대전광역시':'대전', 
                     '인천광역시':'인천','대구광역시':'대구','광주광역시':'광주',
                     '제주특별자치도':'제주','울산광역시':'울산','세종특별자치시':'세종', 
                     '경상남도': '경남', '경기도':'경기','전라북도':'전북','충청남도':'충남', 
                     '경상북도':'경북','강원도':'강원', '전라남도':'전남','충청북도':'충북',
                     '대구시':'대구','부산시':'부산','인천시':'인천'},inplace=True)

In [ ]:
df5

         행정구역      행정구역코드  2103 총인구수  ...  2106 여성 비율  행정구역_시도  행정구역_시군구
0      서울특별시   1100000000    9598484  ...     0.51400       서울
26     부산광역시   2600000000    3372399  ...     0.51040       부산
43     대구광역시   2700000000    2408875  ...     0.50690       대구
52     인천광역시   2800000000    2936461  ...     0.49920       인천
63     광주광역시   2900000000    1445473  ...     0.50520       광주
69     대전광역시   3000000000    1458463  ...     0.50100       대전
75     울산광역시   3100000000    1129254  ...     0.48600       울산
81   세종특별자치시   3600000000     360462  ...     0.50050       세종
82   세종특별자치시   3611000000     360462  ...     0.50050       세종
83       경기도   4100000000   13465837  ...     0.49670       경기
132      강원도   4200000000    1536399  ...     0.49660       강원
151     충청북도   4300000000    1595714  ...     0.49280       충북
167     충청남도   4400000000    2115823  ...     0.48890       충남
185     전라북도   4500000000    1797450  ...     0.50250       전북
202     전라남도   4600000000    1844811  ...     0.49680       전남
225     경상북도   4700000000    2635563  ...     0.49600       경북
251     경상남도   4800000000    3330463  ...     0.49650       경남
275  제주특별자치도   5000000000     673974  ...     0.49830       제주

[18 rows x 60 columns]

In [ ]:
df5.drop(index = 82, axis=1, inplace=True)

In [ ]:
for i in ['2103','2104','2105','2106']:
  df5['%s 2,30대 비율'%i] = df5['%s 20대 비율'%i]+df5['%s 30대 비율'%i]
  df5['%s 4,5,60대 비율'%i] = df5['%s 40대 비율'%i] + df5['%s 50대 비율'%i] + df5['%s 60대 비율'%i]

In [ ]:
df5 = df5[['2103 총인구수', '2104 총인구수', '2105 총인구수', '2106 총인구수',
       '2103 10대 비율', '2104 10대 비율', '2105 10대 비율', '2106 10대 비율',
       '2103 2,30대 비율', '2104 2,30대 비율', '2105 2,30대 비율', '2106 2,30대 비율',
       '2103 4,5,60대 비율', '2104 4,5,60대 비율', '2105 4,5,60대 비율',
       '2106 4,5,60대 비율', '2103 남성 비율', '2104 남성 비율', '2105 남성 비율',
       '2106 남성 비율', '2103 여성 비율', '2104 여성 비율', '2105 여성 비율', '2106 여성 비율',
       '행정구역_시도']]

In [ ]:
melt_df1 = pd.melt(df5, id_vars=['행정구역_시도'], var_name= '성연령', value_name='인구수')

In [ ]:
melt_df1

    행정구역_시도         성연령           인구수
0        서울   2103 총인구수 9598484.00000
1        부산   2103 총인구수 3372399.00000
2        대구   2103 총인구수 2408875.00000
3        인천   2103 총인구수 2936461.00000
4        광주   2103 총인구수 1445473.00000
..      ...         ...           ...
403      전북  2106 여성 비율       0.50250
404      전남  2106 여성 비율       0.49680
405      경북  2106 여성 비율       0.49600
406      경남  2106 여성 비율       0.49650
407      제주  2106 여성 비율       0.49830

[408 rows x 3 columns]

In [ ]:
melt_df1['month'] = melt_df1['성연령'].apply(lambda x : x[2:4])

In [ ]:
melt_df1['성연령분류'] = melt_df1['성연령'].apply(lambda x : x[5:])

In [ ]:
melt_df1

    행정구역_시도         성연령           인구수 month  성연령분류
0        서울   2103 총인구수 9598484.00000    03   총인구수
1        부산   2103 총인구수 3372399.00000    03   총인구수
2        대구   2103 총인구수 2408875.00000    03   총인구수
3        인천   2103 총인구수 2936461.00000    03   총인구수
4        광주   2103 총인구수 1445473.00000    03   총인구수
..      ...         ...           ...   ...    ...
403      전북  2106 여성 비율       0.50250    06  여성 비율
404      전남  2106 여성 비율       0.49680    06  여성 비율
405      경북  2106 여성 비율       0.49600    06  여성 비율
406      경남  2106 여성 비율       0.49650    06  여성 비율
407      제주  2106 여성 비율       0.49830    06  여성 비율

[408 rows x 5 columns]

In [ ]:
melt_df1 = melt_df1[['행정구역_시도', '인구수', 'month', '성연령분류']]

In [ ]:
df_y = melt_df1.pivot(index = ['행정구역_시도','month'], columns = '성연령분류', values='인구수')

In [ ]:
df_y

성연령분류          10대 비율  2,30대 비율  4,5,60대 비율   남성 비율   여성 비율           총인구수
행정구역_시도 month
강원      03    0.08860   0.22280     0.47770 0.50330 0.49670  1536399.00000
        04    0.08840   0.22230     0.47850 0.50320 0.49680  1536175.00000
        05    0.08820   0.22200     0.47920 0.50340 0.49660  1535491.00000
        06    0.08810   0.22170     0.47990 0.50340 0.49660  1535530.00000
경기      03    0.09840   0.27590     0.45420 0.50330 0.49670 13465837.00000
...               ...       ...         ...     ...     ...            ...
충남      06    0.09500   0.23780     0.45180 0.51110 0.48890  2117400.00000
충북      03    0.09270   0.24440     0.46380 0.50730 0.49270  1595714.00000
        04    0.09260   0.24430     0.46430 0.50720 0.49280  1596303.00000
        05    0.09240   0.24400     0.46500 0.50720 0.49280  1596955.00000
        06    0.09220   0.24380     0.46550 0.50720 0.49280  1597503.00000

[68 rows x 6 columns]

### 성/연령별 최종 데이터

In [ ]:
df_y = df_y.reset_index()

In [ ]:
df_y.columns

Index(['행정구역_시도', 'month', '10대 비율', '2,30대 비율', '4,5,60대 비율', '남성 비율',
       '여성 비율', '총인구수'],
      dtype='object', name='성연령분류')

In [ ]:
df_y.columns = ['시도', 'month', '10대 비율', '2,30대 비율', '4,5,60대 비율', '남성 비율',
       '여성 비율', '총인구수']

In [ ]:
df_y.to_pickle('지역별성연령별인구수.pkl')

## 최종 외부 데이터

In [ ]:
final = pd.merge(df_y, df, how = 'inner', on=['시도','month'] )

In [ ]:
final.head()

   시도 month  10대 비율  2,30대 비율  ...      3인      4인      5인            전체
0  강원    03 0.08860   0.22280  ... 0.15220 0.11540 0.04130  735644.00000
1  강원    04 0.08840   0.22230  ... 0.15190 0.11470 0.04120  735644.00000
2  강원    05 0.08820   0.22200  ... 0.15180 0.11440 0.04090  736980.00000
3  강원    06 0.08810   0.22170  ... 0.15150 0.11390 0.04060  738068.00000
4  경기    03 0.09840   0.27590  ... 0.18700 0.17670 0.05260 5719333.00000

[5 rows x 14 columns]

In [ ]:
final.columns

Index(['시도', 'month', '10대 비율', '2,30대 비율', '4,5,60대 비율', '남성 비율', '여성 비율',
       '총인구수', '1인', '2인', '3인', '4인', '5인', '전체'],
      dtype='object')

In [ ]:
final.columns = ['시도', 'month', '10대 비율', '2,30대 비율', '4,5,60대 비율', '남성 비율', '여성 비율',
       '총인구수', '1인', '2인', '3인', '4인', '5인', '전체가구수']

In [ ]:
final.to_csv("demographic.csv", encoding='utf-8')

In [ ]:
final.to_pickle("demographic.pkl")